services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    platform: linux/amd64
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: common
    networks:
      - postgres-network
  pdadmin:
    image: dpage/pgadmin4:8.12.0
    ports:
      - 6432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - postgres-network
    depends_on:
      - postgres

networks:
  postgres-network:
    driver: bridge
