name: Delivery

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
      - run: pnpm exec playwright install chromium --with-deps
      - run: pnpm test
      - run: pnpm run e2e
  delivery:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
      - shell: bash
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
      - run: pnpm run prod-deploy
